### ISSUE TITLE
Please tag branch/master

### ISSUE THREAD

**Issue by darach** [andrewjstone/rafter#31]
Hi Andrew,

We're using rafter in riak_governor and would like to pin our dependencies.
Would it be possible to tag master so we can use that rather than branch/master?

Cheers,

Darach.

**Comment by andrewjstone** [comment]
Hi @darach I just tagged rafter at 0.2.2 off master. A brief word of warning though: While the code works I wouldn't call it production ready. The log is entirely my own wild creation and I haven't touched the majority of the code or used it for anything in well over a year. I should probably add a note at the top of the README.

**Comment by darach** [comment]
Hi Andrew.

Much obliged sir! Thank you.

Cheers,

Darach.

**Comment by andrewjstone** [comment]
You're very welcome!
